---
- hosts: my_cpu
  gather_facts: False
  vars:
    test:
      role1:
        - role1 says hello
        - world
      role2:
        name: role2
        msg: hello_world from role2!
  tasks:
    - name: "Say hello by roles"
      include_role:
        name: say-hello
        tasks_from: "{{ test_dict2.key }}"
      vars:
        inputs: "{{ test_dict2.value }}"
      loop: "{{ test | dict2items }}"
      loop_control:
        loop_var: test_dict2
        label: "{{ test_dict2.key }}"
